# Generated by Django 4.1.7 on 2023-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameID', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(default='', max_length=30, unique=True)),
                ('minPlayingAge', models.IntegerField(default=5)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('gameID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('passwordHash', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=15)),
                ('email', models.CharField(default='', max_length=40, unique=True)),
            ],
        ),
    ]
